---
abstract: 'Run http://validator.w3c.org as a local instance'
author:
  - 'Jan Henning Thorsen - C<< jhthorsen at cpan.org >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: W3C-Validator-Server
no_index:
  directory:
    - inc
    - t
requires:
  CGI::Compile: 0.14
  CGI::Emulate::PSGI: 0.1
  Plack: 0.99
  Plack::Middleware::SSI: 0.1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=W3C-Validator-Server
  homepage: http://search.cpan.org/dist/W3C-Validator-Server
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jhthorsen/w3c-validator-server.git
version: 0.11
